"""
Base Django settings for property_rental project.

Environment-specific settings (SECRET_KEY, DEBUG, ALLOWED_HOSTS, DATABASES)
live in ``dev.py`` and ``prod.py``, which import everything from here via
``from .base import *``.

Generated by 'django-admin startproject' using Django 4.2.4.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings/base.py is two levels below the project package, so we go up
# three levels to reach the project root (the dir containing manage.py).
BASE_DIR = Path(__file__).resolve().parent.parent.parent
VITE_MANIFEST_PATH = BASE_DIR / "rentals" / "static" / "frontend" / "manifest.json"

# Task 6: frontend dist path (only present after `npm run build`). Used
# in TEMPLATES.DIRS below so a fresh clone — where the SPA hasn't been
# built yet — doesn't break Django startup.
FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'


# Application definition
#
# Task 6: ``django_vite`` MUST come before ``django.contrib.staticfiles``
# so its template tags load correctly. It provides the ``vite_hmr_client``
# and ``vite_asset`` tags used by ``spa_index.html``.
INSTALLED_APPS = [
    'rentals',
    'mozilla_django_oidc',
    'rest_framework',
    'django_vite',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTHENTICATION_BACKENDS = ["rentals.oidc.RentalOIDCAuthenticationBackend"]

OIDC_GROUPS_CLAIM = "groups"
OIDC_RP_SCOPES = "openid email profile groups"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_STORE_ACCESS_TOKEN = False
OIDC_STORE_ID_TOKEN = False
OIDC_AUTHORIZATION_MAX_AGE = 300
LOCAL_PASSWORD_AUTH_ENABLED = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise here
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'rentals.middleware.AuthorizationAgeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'property_rental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Task 6: include ``frontend/dist`` (Vite's default build output)
        # if it exists, so a built SPA can be served directly from the
        # filesystem. Falls back to an empty list on a fresh clone —
        # django-vite + APP_DIRS handles the rest.
        'DIRS': [str(FRONTEND_DIST)] if FRONTEND_DIST.exists() else [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'property_rental.wsgi.application'

# Using override settings for User model
AUTH_USER_MODEL = 'rentals.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Use local path for development, will be overridden for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'rentals/static'),
]

# Django 4.2 storage backend configuration.
# WhiteNoise keeps serving compressed, hashed static assets in production.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework (Task 16)
#
# SessionAuthentication is the natural fit for the existing template-rendered
# app: the React frontend will share the same session cookie the login view
# already sets, so no token infrastructure is needed in Phase 1.
# IsAuthenticated is the safe default for a multi-tenant app where every
# record is private to its landlord; per-view/object permissions
# (``rentals.api.permissions.IsOwnerOrReadOnly``) further scope writes.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# django-vite (Task 6)
#
# django-vite generates <script>/<link> tags for the React bundle. In dev
# it points at the Vite dev server (:5173); in prod it reads the manifest
# written by `vite build` (outDir = rentals/static/frontend, see
# frontend/vite.config.ts). ``dev_mode`` is overridden per-environment
# below — defaults here match prod (manifest-driven) so a misconfigured
# env fails closed rather than silently calling the dev server.
#
# - ``static_url_prefix='frontend'`` matches the Vite ``base`` of
#   ``/static/frontend/``. django-vite joins this prefix onto STATIC_URL
#   when building both dev URLs (``http://127.0.0.1:5173/static/frontend/
#   src/main.tsx`` — Vite serves it because base matches) and prod URLs
#   (``/static/frontend/assets/index-<hash>.js`` — Django staticfiles
#   serves it from ``rentals/static/frontend/``).
# - ``manifest_path`` points at the file written by ``vite build``
#   (``manifest: 'manifest.json'`` inside outDir). Without this,
#   django-vite looks in STATIC_ROOT which we don't populate during local
#   dev/test.
DJANGO_VITE = {
    "default": {
        # overridden to True in dev.py
        "dev_mode": False,
        "dev_server_protocol": "http",
        "dev_server_host": "127.0.0.1",
        "dev_server_port": 5173,
        "manifest_path": str(VITE_MANIFEST_PATH),
        "static_url_prefix": "frontend",
    },
}


# Logging (Phase 4 Task 4, 2026-07-19)
#
# Replaces the stray ``print()`` calls that were scattered through
# ``rentals.services.fx`` and ``rentals.utils``. Per-module loggers
# (``logging.getLogger(__name__)``) inherit the root handler + level
# configured here. ``disable_existing_loggers=False`` keeps Django's
# default loggers (``django.request``, ``django.security``, etc.)
# intact. Level/handlers can be overridden per-environment in
# ``dev.py`` / ``prod.py``.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
