# Generated by Django 4.2.4 on 2023-08-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=None, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('rented', 'Rented out'), ('not_rented', 'Idle')], default='not_rented', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='value_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
