# Generated by Django 4.2.4 on 2023-10-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_property_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='FX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('USDEUR', models.DecimalField(decimal_places=4, max_digits=10)),
                ('USDGBP', models.DecimalField(decimal_places=4, max_digits=10)),
                ('RUBUSD', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
