# Generated by Django 4.2.4 on 2023-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_fx_rubusd_alter_fx_usdeur_alter_fx_usdgbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fx',
            name='RUBUSD',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='USDEUR',
        ),
        migrations.RemoveField(
            model_name='fx',
            name='USDGBP',
        ),
        migrations.AddField(
            model_name='fx',
            name='EURUSD',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='GBPUSD',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='USDRUB',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
