# Generated by Django 4.2.4 on 2023-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_fx_rubusd_remove_fx_usdeur_remove_fx_usdgbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx',
            name='EURUSD',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fx',
            name='GBPUSD',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fx',
            name='USDRUB',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
