# Generated by Django 4.2.4 on 2023-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_fx_eurusd_alter_fx_gbpusd_alter_fx_usdrub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chart_frequency',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='chart_timeline',
            field=models.CharField(default='6m', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='use_default_currency_for_all_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lease_rent',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
    ]
