# Generated by Django 4.2.4 on 2023-09-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rename_value_property_property_value_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='property',
        #     old_name='value_currency',
        #     new_name='currency',
        # ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('USD', 'US$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(default='dummy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(default='dummy', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('tax', 'Tax'), ('capex', 'Capex'), ('management', 'Management'), ('electricity', 'Electricity'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
