# Generated by Django 4.2.4 on 2023-09-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rename_value_currency_property_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='value_currency',
            new_name='currency',
        ),
    ]
