# Generated by Django 4.2.4 on 2023-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_user_chart_frequency_user_chart_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digits',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
