# Generated by Django 4.2.4 on 2023-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_user_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digits',
            field=models.IntegerField(default=0),
        ),
    ]
