# Generated by Django 4.2.4 on 2023-10-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rename_value_currency_property_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='property_owned',
        ),
    ]
