# Generated by Django 4.2.4 on 2023-09-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rename_value_currency_property_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('tax', 'Tax'), ('capex', 'Capex'), ('management', 'Management'), ('electricity', 'Electricity'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
