# Generated by Django 4.2.4 on 2023-10-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='property_owned',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='rentals.tenant'),
        ),
    ]
