# Generated by Django 4.2.4 on 2023-12-02 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_user_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digits',
            field=models.IntegerField(default=0, error_messages={'max_value': 'The value for digits must be less than or equal to 6.'}, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
