# Generated by Django 4.2.4 on 2023-10-02 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_alter_transaction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent (income)'), ('tax', 'Tax (expense)'), ('capex', 'Capex (expense)'), ('management', 'Management (expense)'), ('electricity', 'Electricity (expense)'), ('utilities', 'Utilities (expense)'), ('internet', 'Internet (expense)'), ('other', 'Other (expense)')], default='rent', max_length=20),
        ),
    ]
