# Generated by Django 4.2.4 on 2023-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent (income)'), ('tax', 'Tax (expense)'), ('capex', 'Capex (expense)'), ('management', 'Management (expense)'), ('electricity', 'Electricity (expense)'), ('utilities', 'Utilities (expense)'), ('internet', 'Internet (expense)'), ('other', 'Other (expense)')], default='rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='rent', max_length=20),
        ),
    ]
