# Generated by Django 4.2.4 on 2026-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_transaction_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
