# Generated by Django 4.2.4 on 2026-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_user_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='from_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fx',
            name='to_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
