# Generated by Django 4.2.4 on 2023-10-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='rentals.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('tax', 'Tax'), ('capex', 'Capex'), ('management', 'Management'), ('electricity', 'Electricity'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
