# Generated by Django 4.2.4 on 2023-10-04 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_remove_property_tenant_tenant_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
