# Generated by Django 4.2.4 on 2023-10-04 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_tenant_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payday',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(27)]),
        ),
    ]
