# Generated by Django 4.2.4 on 2026-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_fx_drop_wide_columns_tighten_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('tax', 'Tax'), ('capex', 'Capex'), ('management', 'Management'), ('electricity', 'Electricity'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('cost_reimbursement', 'Cost reimbursement'), ('other_expenses', 'Other Expenses')], default='rent', max_length=20),
        ),
    ]
