# Generated by Django 4.2.4 on 2023-10-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_alter_tenant_payday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease_rent',
        ),
        migrations.CreateModel(
            name='Lease_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rent_set', models.DateField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='rentals.tenant')),
            ],
        ),
    ]
