# Generated by Django 4.2.4 on 2023-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_remove_tenant_lease_rent_lease_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease_rent',
            name='currency',
            field=models.CharField(choices=[('USD', 'US$'), ('EUR', '€'), ('GBP', '£'), ('RUB', '₽')], default='USD', max_length=3, null=True),
        ),
    ]
