# Generated by Django 4.2.4 on 2023-10-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_lease_rent_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='currency',
        ),
    ]
