# Generated by Django 4.2.4 on 2023-10-05 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0024_remove_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(27)]),
        ),
    ]
