# Generated by Django 4.2.4 on 2023-10-05 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0025_alter_tenant_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payday',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(27)]),
        ),
    ]
