# Generated by Django 4.2.4 on 2023-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_alter_tenant_payday'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.DateField(blank=True, help_text='The month and year for this transaction', null=True),
        ),
    ]
