# Generated by Django 4.2.4 on 2026-08-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0026_normalize_legacy_lease_rent_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCLogoutReplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.URLField(max_length=500)),
                ("jti", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="OIDCSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(db_index=True, max_length=255)),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="rentals.oidcidentity",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="oidclogoutreplay",
            constraint=models.UniqueConstraint(
                fields=("issuer", "jti"), name="unique_oidc_logout_issuer_jti"
            ),
        ),
        migrations.AddConstraint(
            model_name="oidcsession",
            constraint=models.UniqueConstraint(
                fields=("identity", "sid", "session_key"),
                name="unique_oidc_identity_sid_session",
            ),
        ),
    ]
